# NOTAS DE R ADICIONALES:

# LIBRERÍA DE GESTIÓN DE FECHAS: LUBRIDATE

# LIBRERÍA FEATHER --> PARA GUARDAR: COMPATIBLE CON PYTHON (COMÚN PYTHON Y R)

#LIBRERÍA FOREIGN --> PARA LEER Y GUARDAR ARCHIVOS DE EXCEL

# LIBRERÍA RVEST --> PARA WEB SCRAPPING

# LIBRERÍA DPLYR --> PARA GESTIÓN DE DATAFRAMES

# LIBRERÍA SHINY --> PARA CREAR DASHBOARDS